### ISSUE TITLE
Course complete event

### ISSUE THREAD

**Issue by CinecaElearning** [LearningLocker/Moodle-xAPI-Translator#36]
**Motive**
the course completed event is not an event sent

**Result**
In the following PR, I added a new course completed event with the relative test.

**Additional information**
{{additionalInfo}}

**Comment by caperneoignis** [comment]
I actually was coming here to make the same request. Right now, if I'm building a report using learning locker, I have to check for certain events as to whether or not a user completed a course. So if I'm building a course completion report, there is a lot of actual conditions, I have to put in to find the course completion information. Take for instance, Manger Training which has a quiz known as the quiz. To tell whether or not a person completed the manager training, I have to go to the quiz, see what that user scored, and if that quiz is actually in that training, and not in another training, but with the same name. Kinda hard. I've been working on the event, and I think it looks right, it passes the test you have in the different translators. But seems really easy, so not sure if it's actually done.

**Comment by jlowe64** [comment]
There was another PR for this event but it never got completed, so if you do finish it, do a PR and we can review it for integration!

**Comment by caperneoignis** [comment]
Okay! I have to modify the moodle-log-expander to have course completed, and also the test for it, but the xapi-translator and xapi-recipe all are done, with test. I'll also make sure I go through and make comments and ensure my coding style isn't complete bullocks.

**Comment by jlowe64** [comment]
I really appreciate your hard work!

**Comment by caperneoignis** [comment]
I'm a little busy today, with another item on my list, worse comes to worse I'll start tonight or tomorrow. I have Jenkins so I can run test on it to make sure it works. When would you like this by? I'll try and shoot for next week if possible.

**Comment by jlowe64** [comment]
I'll be doing a bug smashing release this week, and hopefully start on a feature release very soon!

**Comment by jlowe64** [comment]
(with that said, when you get the time is fine)

**Comment by caperneoignis** [comment]
Should the example document from Course Completed come out the same as Event.json (in the moodle-log-expander)? The only difference should be the event->eventname = "core/event/course_completed'; The other two are coming out fine, it's just this one is not looking right. I attached the example document zip, just in case anyone wants to look. But I'm extending event.php, since the only change is the course is completed.
[examples.zip](https://github.com/LearningLocker/Moodle-xAPI-Translator/files/273557/examples.zip)

**Comment by CinecaElearning** [comment]
Hello @caperneoignis,
you can also use our work (which is the PR mentioned above). The PR was covering a bunch of issues and we stopped before adding an assert for the tests (the issue was already covered).

**Comment by jlowe64** [comment]
I agree with @CinecaElearning if you wanted to pick up their work that would be a lot less for you to do. There's only a little bit left to do.

**Comment by caperneoignis** [comment]
Ok! Not a problem.

**Comment by caperneoignis** [comment]
Do we have a programmer chat some where? That way I don't fill up this with a bunch of junk?

**Comment by davidpesce** [comment]
Incorporated as of v1.4.0
