### ISSUE TITLE
user identified by email

### ISSUE THREAD

**Issue by CinecaElearning** [LearningLocker/Moodle-xAPI-Translator#37]
**Motive**
the user can be identified by an email or by account details on the Moodle platform.

**Result**
in the code inside the following PR, we added the possibility to send the email.

**Additional information**
{{additionalInfo}}

**Comment by davidpesce** [comment]
Unfortunately, the PRs submitted for this issue do not work properly and the PR submitter is not responding. I have opened a new issue in the main repo to address this functionality in the future.
