### ISSUE TITLE
CourseCompleted event contains wrong Actor

### ISSUE THREAD

**Issue by bvukas** [LearningLocker/Moodle-xAPI-Translator#49]
\core\event\course_completed event is being fired from cron. Since the cron is usually ran as system admin, the Actor in statement contains system admin user, instead of the user that actually completed the course.

In CourseCompleted->read method user_id, user_url, and user_name should probably be taken from relateduser, instead of user.

**Comment by bvukas** [comment]
I've created Pull Request #51

**Comment by ryansmith94** [comment]
Hey @bvukas thanks for reporting the issue. Is the relateduser always set as the correct user or is only when the cron is used?

**Comment by davidpesce** [comment]
Resolved in v1.4.1
